# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dadf5cf00e692acaea1a04991be3af1f784f0e61474588a6d25ddddf939660c93afe68eced9752858a82482fbd6b454c28e4601272b50bc7050c13aa1830c21

test:
  secret_key_base: 1bcf0d4fbe619c8f947028527f9ec8843030d3544cc8f639eb1065ae457520a451ddc90b620e2b7e33f44355beed13ab7dcb1443b23e3c44beaf201b4c4e9a10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
